import { DocumentCase, ScanRecord } from "./types";

export const recentScans: ScanRecord[] = [
  {
    id: "SCN-88213",
    name: "Marcus Chen",
    nationality: "SGP",
    documentType: "Passport",
    timestamp: "2026-09-09T08:12:00Z",
    status: "cleared",
    riskScore: 4,
    officer: "R. Alvarez",
  },
  {
    id: "SCN-88214",
    name: "Nadia Petrova",
    nationality: "RUS",
    documentType: "Passport",
    timestamp: "2026-09-09T08:19:00Z",
    status: "high_risk",
    riskScore: 87,
    officer: "R. Alvarez",
  },
  {
    id: "SCN-88215",
    name: "Ahmed Al-Farsi",
    nationality: "ARE",
    documentType: "Visa",
    timestamp: "2026-09-09T08:24:00Z",
    status: "cleared",
    riskScore: 11,
    officer: "T. Okafor",
  },
  {
    id: "SCN-88216",
    name: "Elena Vasquez",
    nationality: "MEX",
    documentType: "Passport",
    timestamp: "2026-09-09T08:31:00Z",
    status: "pending",
    riskScore: 0,
    officer: "T. Okafor",
  },
  {
    id: "SCN-88217",
    name: "Liam O'Sullivan",
    nationality: "IRL",
    documentType: "National ID",
    timestamp: "2026-09-09T08:36:00Z",
    status: "cleared",
    riskScore: 6,
    officer: "J. Kim",
  },
  {
    id: "SCN-88218",
    name: "Priya Raman",
    nationality: "IND",
    documentType: "Passport",
    timestamp: "2026-09-09T08:44:00Z",
    status: "high_risk",
    riskScore: 92,
    officer: "J. Kim",
  },
  {
    id: "SCN-88219",
    name: "Viktor Nowak",
    nationality: "POL",
    documentType: "Visa",
    timestamp: "2026-09-09T08:51:00Z",
    status: "cleared",
    riskScore: 9,
    officer: "R. Alvarez",
  },
  {
    id: "SCN-88220",
    name: "Grace Mwangi",
    nationality: "KEN",
    documentType: "Passport",
    timestamp: "2026-09-09T08:58:00Z",
    status: "pending",
    riskScore: 0,
    officer: "T. Okafor",
  },
];

export const dashboardSummary = {
  totalScansToday: 214,
  fakesDetected: 9,
  avgProcessingTimeSeconds: 3.8,
  scansTrend: 12.4,
  fakesTrend: -2.1,
  timeTrend: -8.6,
};

// The active case loaded into the Screening Terminal for the demo.
// This intentionally contains a DOB mismatch and two tampered regions
// so all three result panels have something meaningful to display.
export const mockDocumentCase: DocumentCase = {
  documentId: "SCN-88214",
  imageUrl:
    "https://images.unsplash.com/photo-1584036561566-baf8f5f1b144?q=80&w=1200&auto=format&fit=crop",
  submittedAt: "2026-09-09T08:19:00Z",
  tamperedRegions: [
    {
      id: "region-1",
      label: "Error Level Analysis: High Noise",
      detail: "Pixel-level compression inconsistency detected around the date-of-birth field.",
      confidence: 94,
      left: 15,
      top: 78,
      width: 34,
      height: 9,
      severity: "high",
    },
    {
      id: "region-2",
      label: "Font Kerning Anomaly",
      detail: "Character spacing in surname deviates from ICAO 9303 reference font metrics.",
      confidence: 81,
      left: 15,
      top: 34,
      width: 46,
      height: 8,
      severity: "medium",
    },
    {
      id: "region-3",
      label: "Photo Substitution Artifact",
      detail: "Ghosting halo around portrait edge suggests digital splice.",
      confidence: 76,
      left: 62,
      top: 14,
      width: 30,
      height: 42,
      severity: "medium",
    },
  ],
  fields: [
    { field: "Surname", viz: "PETROVA", mrz: "PETROVA", match: true },
    { field: "Given Names", viz: "NADIA", mrz: "NADIA", match: true },
    { field: "Passport No.", viz: "74RU829104", mrz: "74RU829104", match: true },
    { field: "Nationality", viz: "RUS", mrz: "RUS", match: true },
    { field: "Date of Birth", viz: "1995-05-12", mrz: "1994-05-12", match: false },
    { field: "Sex", viz: "F", mrz: "F", match: true },
    { field: "Date of Expiry", viz: "2029-03-18", mrz: "2029-03-18", match: true },
    { field: "Personal No.", viz: "—", mrz: "8827301944", match: false },
  ],
  riskScore: 87,
  riskFactors: [
    { label: "MRZ Checksum", detail: "Digit verification on personal number field", score: 100, status: "fail" },
    { label: "Face Match", detail: "Portrait vs. live capture similarity", score: 98, status: "pass" },
    { label: "DOB Consistency", detail: "VIZ vs MRZ date-of-birth agreement", score: 12, status: "fail" },
    { label: "Font Forensics", detail: "Glyph metrics vs ICAO 9303 reference", score: 64, status: "warn" },
    { label: "Watchlist Screen", detail: "Cross-reference against alert database", score: 100, status: "pass" },
    { label: "Document Template", detail: "Layout match to issuing authority spec", score: 88, status: "pass" },
  ],
  verdictHint: "reject",
};
